
// controllers/clientController.js (FINAL VERSION)
import Client from "../models/Client.js";
import bcrypt from "bcryptjs"; 
import fs from "fs/promises"; // 💡 For deleting files from the system
import path from "path";     // 💡 For constructing file paths


export const addClient = async (req, res) => {
    // ... [Your existing addClient logic]
    try {
        const { 
            workerId, password, phoneNumber, passportNumber, 
            clientName, email, categoryId, categoryName, designation, remarks 
        } = req.body;
        
        const hashedPassword = await bcrypt.hash(password, 10);
        const profileImage = req.file ? req.file.filename : "default-client.png";
        
        const newClient = await Client.create({
            workerId,
            password: hashedPassword,
            profileImage,
            phoneNumber,
            passportNumber,
            clientName,
            email,
            categoryId,
            categoryName,
            designation, 
            remarks 
        });

        newClient.password = undefined; 
        
        res.status(201).json({ 
            message: "Client Added Successfully", 
            client: newClient 
        });
        
    } catch (error) {
        if (error.code === 11000) {
            const key = Object.keys(error.keyValue)[0];
            return res.status(400).json({ 
                error: `${key.charAt(0).toUpperCase() + key.slice(1)} already exists.`,
                details: error.message
            });
        }
        res.status(500).json({ error: error.message });
    }
};

// 📝 Get All Clients
export const getAllClients = async (req, res) => {
    // ... [Your existing getAllClients logic]
    try {
        const clients = await Client.find()
            .select("-password")
            .sort({ createdAt: -1 }); 
            
        res.json({ clients });
        
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// 📝 Update Client Details (Basic fields + Status fields)
export const updateClientDetails = async (req, res) => {
    // ... [Your existing updateClientDetails logic]
    try {
        const { id } = req.params;
        
        const allowedUpdates = [
            'phoneNumber', 'passportNumber', 'clientName', 
            'email', 'categoryId', 'categoryName', 'designation', 
            'remarks', 'selectionEmailSent', 'confirmationEmailSent'
        ];
        
        const updateData = {};
        for (const key of allowedUpdates) {
            if (req.body[key] !== undefined) {
                updateData[key] = req.body[key];
            }
        }
        
        const updatedClient = await Client.findByIdAndUpdate(
            id,
            updateData,
            { new: true, runValidators: true }
        ).select("-password");
        
        if (!updatedClient) {
            return res.status(404).json({ message: "Client not found" });
        }
        
        res.json({ 
            message: "Client Updated Successfully", 
            client: updatedClient 
        });
        
    } catch (error) {
        if (error.code === 11000) {
            const key = Object.keys(error.keyValue)[0];
            return res.status(400).json({ 
                error: `${key.charAt(0).toUpperCase() + key.slice(1)} already exists.`,
                details: error.message
            });
        }
        res.status(500).json({ error: error.message });
    }
};

// 📝 Delete Client
export const deleteClient = async (req, res) => {
    // ... [Your existing deleteClient logic]
    try {
        const { id } = req.params;
        
        const client = await Client.findByIdAndDelete(id);
        
        if (!client) {
            return res.status(404).json({ message: "Client not found" });
        }
        
        // ⚠️ IMPROVEMENT: Add logic here to delete all related documents from the file system
        
        res.json({ message: "Client Deleted Successfully" });
        
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// 📝 Handle Document Upload
export const addClientDocument = async (req, res) => {
    // ... [Your existing addClientDocument logic]
    try {
        const { id } = req.params;
        
        if (!req.file) {
            return res.status(400).json({ message: "No file uploaded" });
        }
        
        const { originalname, filename } = req.file;
        
        const updatedClient = await Client.findByIdAndUpdate(
            id,
            { $push: { 
                documents: { 
                    documentName: originalname, 
                    filePath: filename // Storing the filename generated by Multer
                } 
            } },
            { new: true, runValidators: true }
        ).select("-password");

        if (!updatedClient) {
            return res.status(404).json({ message: "Client not found" });
        }

        res.json({ 
            message: "Document Added Successfully", 
            client: updatedClient 
        });
        
    } catch (error) {
        console.error("Document Upload Error:", error);
        res.status(500).json({ error: error.message });
    }
};

// --- 💡 NEW & COMPLETE DOCUMENT MANAGEMENT ---

// 📝 Get Client Documents (Now fully implemented)
export const getClientDocuments = async (req, res) => {
    try {
        const { id } = req.params;
        
        // Find client and only return the documents array
        const client = await Client.findById(id).select("clientName documents");

        if (!client) {
            return res.status(404).json({ message: "Client not found" });
        }

        res.json({
            clientName: client.clientName,
            documents: client.documents
        });

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// 📝 Delete Client Document (Now fully implemented)
export const deleteClientDocument = async (req, res) => {
    try {
        const { id, docId } = req.params;
        
        // 1. Find the client
        const client = await Client.findById(id);
        if (!client) return res.status(404).json({ message: "Client not found" });

        const docEntry = client.documents.id(docId); 
        if (!docEntry) return res.status(404).json({ message: "Document entry not found" });

        const filename = docEntry.filePath; 

        // 2. Remove entry from the MongoDB array
        client.documents.pull({ _id: docId });
        await client.save();

        // 3. Delete the physical file from the 'uploads' folder
        // process.cwd() ensures the path is relative to the project root
        const filePath = path.join(process.cwd(), 'uploads', filename);

        try {
            await fs.unlink(filePath);
            console.log(`Successfully deleted file: ${filePath}`);
        } catch (fileError) {
            // File not found on disk, but DB entry is gone, so log and continue
            console.warn(`Could not delete file ${filename} from disk (possibly already deleted):`, fileError.message);
        }

        res.json({ message: "Document deleted successfully" });

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};